name: simformer
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.1
  - torchvision
  - torchaudio
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - pandas
  - scikit-learn
  - tqdm
  - pyyaml
  - h5py
  - pip
  - pip:
    - einops
    - hydra-core
    - omegaconf
    - wandb
    - tensorboard
